# Generated by Django 5.1.1 on 2024-09-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='lobby_name',
            field=models.CharField(default='Unknown', max_length=64, verbose_name='lobby_display_name'),
        ),
    ]
