# Generated by Django 5.1.2 on 2024-10-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_alter_tournament_number_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='pseudo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
