# Generated by Django 5.1 on 2024-08-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='1970-12-25 00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='1970-12-25 00:00'),
            preserve_default=False,
        ),
    ]
