# Generated by Django 5.1.1 on 2024-09-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_user_friends_alter_user_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='tournament unique id'),
        ),
    ]
