name: transcendence

#Env file template
# POSTGRES_USER=postgres
# POSTGRES_PASSWORD=postgres
# POSTGRES_HOST=db
# POSTGRES_PORT=5432

# POSTGRES_DB_AUTH=auth
# POSTGRES_DB_USERS=users

services:

  nginx:
    container_name: nginx_c
    image: nginx
    ports:
      - 8083:443
      - 8080:80
    volumes:
      - ./frontend/:/www/html/
      - ./data/logs/nginx/:/var/log/nginx/:rw
      - ./srcs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/keys/ssl/ssl.crt:/etc/certificate/ssl.crt
    secrets:
      - ssl-key
    depends_on:
      - users_api

  db:
    container_name: db_c
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./srcs/scripts/db_entrypoint:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DB_AUTH},${POSTGRES_DB_USERS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  auth_api:
    container_name: auth_api_c
    build:
      context: ./srcs/django_builds
      target: django_restapi
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./srcs/backend/auth/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB_AUTH}

  users_api:
    container_name: users_api_c
    build:
      context: ./srcs/django_builds
      target: django_restapi
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - ./srcs/backend/users/:/code
      - ./data/keys/rsa/pub.pem:/etc/certificate/pub.pem
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB_USERS}
    secrets:
      - rsa-key

  redis:
    container_name: redis_c
    image: redis
    ports:
      - "8008:6379"

  websocket_example:
    container_name: websocket_c
    build:
      context: ./srcs/django_builds
      target: django_websocketapi
    ports:
      - "8002:8002"
    command: python3 manage.py runserver 0.0.0.0:8002
    depends_on:
        - redis
    volumes:
      - ./srcs/backend/websocket_example/:/code



  # web2:
  #   container_name: web2_c
  #   build:
  #     context: ./srcs/django_builds
  #     target: django_main
  #   command: python manage.py runserver 0.0.0.0:8001
  #   volumes:
  #     - ./srcs/backend/webapp/code:/code
  #   ports:
  #     - "8001:8001"
  #   env_file: ./.env
  #   depends_on:
  #     - db

secrets:
  ssl-key:
    file: ./data/keys/ssl/ssl.key
  rsa-key:
    file: ./data/keys/rsa/key.pem
